import type { Video } from "youtube-sr";

export type AudioCandidate = {
  id: string;
  title: string;
  author: string;
  url: string;
  durationMs: number;
  thumbnail: string | null;
};

type Rule = {
  /** Se evalúa sobre título + canal, en minúsculas y sin acentos. */
  pattern: RegExp;
  weight: number;
  /** Si la propia petición del usuario encaja aquí, la regla no se aplica (pidió eso a propósito). */
  unlessQuery?: RegExp;
};

/* ───────────────────── Lo que queremos: audio oficial ───────────────────── */

const POSITIVE: Rule[] = [
  { pattern: /\btopic\b/, weight: 30 }, // canal auto-generado "Artista - Topic": audio puro
  { pattern: /provided to youtube|auto-?generated by youtube/, weight: 20 },
  { pattern: /official audio|audio oficial|\(audio\)|\[audio\]/, weight: 25 },
  { pattern: /\baudio\b/, weight: 10 },
  { pattern: /visuali[sz]er|visualizador/, weight: 8 }, // arte estático + audio oficial
  { pattern: /lyric|\bletra\b|con letra/, weight: 18 }, // los lyric videos llevan el audio original; compensa la penalización de "video"
  { pattern: /\bofficial\b|\boficial\b/, weight: 4 },
];

/* ───────────────────── Lo que NO queremos si no se pide ───────────────────── */

const NEGATIVE: Rule[] = [
  // Versiones alteradas
  { pattern: /\bremix|\brmx\b|bootleg|mashup|\bflip\b|\bvip mix|\brework/, weight: 45, unlessQuery: /\bremix|\brmx\b|bootleg|mashup|\bflip\b/ },
  { pattern: /sped ?up|speed ?up|slowed|reverb|nightcore|\b8d\b|bass ?boost|daycore/, weight: 40, unlessQuery: /\bsped|\bspeed|\bslowed|\breverb|nightcore|\b8d\b|bass ?boost/ },
  { pattern: /\bedit\b|\bedits\b|\bversion\b|\bversao\b/, weight: 20, unlessQuery: /\bedit\b|\bversion\b|\bversao\b/ },
  { pattern: /lo-?fi|chill(hop|ed)?\b|tiktok|tik tok/, weight: 25, unlessQuery: /lo-?fi|\bchill|tiktok|tik tok/ },
  // Otras interpretaciones
  { pattern: /\bcover\b|karaoke|instrumental|acapella|a capella|acoustic|acustic[ao]|unplugged/, weight: 35, unlessQuery: /\bcover|karaoke|instrumental|acapella|a capella|acoustic|acustic|unplugged/ },
  { pattern: /\bpiano\b|\bguitar\b|guitarra|tutorial|lesson|leccion|how to play|como tocar|drum cover|bateria/, weight: 30, unlessQuery: /\bpiano|\bguitar|guitarra|tutorial|\blesson|leccion|\btocar|\bdrum|bateria/ },
  { pattern: /\breact(s|ing|ion)?\b|reaccion|parod[iy]|fan ?made|medley|mashup/, weight: 30, unlessQuery: /\breact|reaccion|\bparod|fan ?made|medley/ },
  // Directos
  { pattern: /\blive\b|en vivo|en directo|live at|live from|live session|concert|concierto|\btour\b|festival|\bmtv\b|unplugged/, weight: 30, unlessQuery: /\blive\b|en vivo|en directo|\bdirecto|\bconcert|concierto|\btour\b|festival|\bmtv\b|unplugged/ },
  // Videoclips
  { pattern: /official (music )?video|video oficial|music video|videoclip|video clip|clip oficial|\bvideo\b/, weight: 22, unlessQuery: /\bvideo|\bclip\b/ },
  { pattern: /\bdance\b|choreograph|coreograf|behind the scenes|detras de camaras|making of|trailer|teaser|snippet|preview|interview|entrevista/, weight: 25, unlessQuery: /\bdance\b|\bbaile|choreograph|coreograf|\bbehind|\bdetras|\bmaking|trailer|teaser|snippet|preview|interview|entrevista/ },
  // Formatos que no son "una canción"
  { pattern: /full album|album completo|disco completo|\b\d+\s*(hours?|horas?)\b|1 hour|1 hora|\bloop\b|extended|extendid[ao]|\bmix\b|\bdj set\b|\bmegamix|playlist|compilation|recopilacion|top \d+|mejores|greatest hits/, weight: 35, unlessQuery: /\balbum|completo|\bhour|\bhora|\bloop|extended|extendid|\bmix\b|dj set|megamix|playlist|\bcompil|\brecopil|top \d+|mejores|greatest/ },
  { pattern: /#?shorts\b|vertical video/, weight: 30 },
  { pattern: /\bvevo\b/, weight: 6 }, // VEVO es oficial, pero casi siempre videoclip; el título decide
];

const STOPWORDS = new Set([
  "de", "del", "la", "el", "los", "las", "un", "una", "y", "e", "o", "u", "a", "en", "con", "por", "para", "que",
  "the", "of", "and", "or", "feat", "ft", "featuring", "x", "vs", "con", "cancion", "song", "tema", "musica", "music",
  "official", "oficial", "audio", "video", "pon", "ponme", "reproduce", "play",
]);

const MIN_SONG_MS = 45_000;
const MAX_SONG_MS = 15 * 60_000;

/**
 * Puntúa un candidato. `query` es lo que pidió el usuario: sirve para no
 * penalizar lo que pidió a propósito (un remix, un directo…) y para comprobar
 * que el resultado se parece a lo que buscó.
 */
export function audioPickScore(
  title: string,
  author: string,
  options: {
    query?: string;
    durationMs?: number;
    typicalDurationMs?: number;
    /** Peso de cada palabra de la petición (ver `tokenWeights`). Sin él, todas pesan igual. */
    tokenWeights?: Map<string, number>;
  } = {},
): number {
  const text = fold(`${title} ${author}`);
  const query = fold(options.query ?? "");
  let score = 0;
  // "theweeknd" debe encontrar "The Weeknd": comparamos también sin espacios.
  const compact = text.replace(/\s+/g, "");
  const has = (token: string) => text.includes(token) || compact.includes(token);

  // Relevancia: ¿aparecen las palabras de la petición en el título o el canal?
  // Un "Official Audio" de OTRA canción no nos sirve, así que los bonus de
  // audio se escalan por relevancia y las palabras que faltan penalizan.
  const tokens = queryTokens(query);
  const weightOf = (token: string) => options.tokenWeights?.get(token) ?? 1;
  const totalWeight = tokens.reduce((sum, token) => sum + weightOf(token), 0);
  const foundWeight = tokens.filter(has).reduce((sum, token) => sum + weightOf(token), 0);
  const relevance = totalWeight > 0 ? foundWeight / totalWeight : 1;

  let positive = 0;
  for (const rule of POSITIVE) {
    if (rule.pattern.test(text)) positive += rule.weight;
  }
  score += Math.round(positive * relevance);

  for (const rule of NEGATIVE) {
    const matches = rule.pattern.test(text);
    const requested = Boolean(rule.unlessQuery && query && rule.unlessQuery.test(query));
    if (requested) {
      // El usuario pidió esta variante a propósito ("remix", "en vivo"…):
      // premiamos lo que la cumple y penalizamos lo que no.
      score += matches ? 20 : -30;
      continue;
    }
    if (matches) score -= rule.weight;
  }

  if (tokens.length) {
    score += Math.round(relevance * 20 - (1 - relevance) * 60);
  }

  // Duración: ni shorts ni loops de una hora, y parecida a la de los demás resultados.
  const duration = options.durationMs ?? 0;
  if (duration > 0) {
    const longRequested = /album|completo|hour|hora|loop|extended|extendid|\bmix\b|dj set|megamix|playlist|compil/.test(query);
    if (duration < MIN_SONG_MS) score -= 25;
    if (duration > MAX_SONG_MS && !longRequested) score -= 25;
    const typical = options.typicalDurationMs ?? 0;
    if (typical > 0 && Math.abs(duration - typical) > typical * 0.35) score -= 12;
  }

  return score;
}

export function pickBestAudioTracks<T extends AudioCandidate>(
  candidates: T[],
  limit: number,
  query?: string,
): T[] {
  const unique = dedupeCandidates(candidates);
  const typical = medianDuration(unique);
  const weights = tokenWeights(query ?? "", unique);
  return unique
    .map((item) => ({
      item,
      score: audioPickScore(item.title, item.author, {
        query,
        durationMs: item.durationMs,
        typicalDurationMs: typical,
        tokenWeights: weights,
      }),
    }))
    .sort(
      (a, b) =>
        b.score - a.score ||
        Math.abs(a.item.durationMs - typical) - Math.abs(b.item.durationMs - typical),
    )
    .slice(0, limit)
    .map(({ item }) => item);
}

export function candidateFromVideo(video: Video): AudioCandidate | null {
  if (!video.url || video.live || video.private) return null;
  return {
    id: video.id || video.url,
    title: video.title || video.url,
    author: video.channel?.name || "YouTube",
    url: video.url,
    durationMs: video.duration || 0,
    thumbnail: video.thumbnail?.url ?? video.thumbnail?.displayThumbnailURL() ?? null,
  };
}

function queryTokens(query: string): string[] {
  return Array.from(
    new Set(
      query
        .replace(/https?:\/\/\S+/g, " ")
        .split(/[^a-z0-9ñ]+/)
        .filter((token) => token.length >= 2 && !STOPWORDS.has(token)),
    ),
  );
}

/**
 * Peso de cada palabra de la petición según lo que discrimina entre los
 * candidatos: el nombre del artista aparece en casi todos (pesa poco), el
 * título de la canción solo en los correctos (pesa mucho).
 */
function tokenWeights(query: string, candidates: AudioCandidate[]): Map<string, number> {
  const tokens = queryTokens(fold(query));
  const weights = new Map<string, number>();
  if (!candidates.length) return weights;
  const texts = candidates.map((item) => fold(`${item.title} ${item.author}`).replace(/\s+/g, ""));
  for (const token of tokens) {
    const hits = texts.filter((text) => text.includes(token)).length;
    const frequency = hits / texts.length;
    weights.set(token, 1.2 - frequency); // 0.2 (en todos) … 1.2 (en ninguno)
  }
  return weights;
}

function medianDuration(candidates: AudioCandidate[]): number {
  const durations = candidates
    .map((item) => item.durationMs)
    .filter((ms) => ms >= MIN_SONG_MS && ms <= MAX_SONG_MS)
    .sort((a, b) => a - b);
  if (!durations.length) return 0;
  const middle = Math.floor(durations.length / 2);
  return durations.length % 2 ? durations[middle]! : Math.round((durations[middle - 1]! + durations[middle]!) / 2);
}

function dedupeCandidates<T extends AudioCandidate>(candidates: T[]): T[] {
  const seen = new Set<string>();
  const out: T[] = [];
  for (const item of candidates) {
    const key = item.id || item.url;
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}

function fold(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase();
}
